// This file contains all the option-related variables used in CustomListManager.

export const statusItems: string[] = [
	"Watching",
	"Reading",
	"Completed",
	"Paused",
	"Planning",
	"Dropped",
];

export const scoreItems: string[] = ["10", "9", "8", "7", "6", "5", "4", "3", "2", "1", "below 5"];

export const miscItemsAnime: string[] = ["Rewatched", "Adult (18+)"];

export const miscItemsManga: string[] = ["Reread", "Adult (18+)"];

export const formatItemsAnime: string[] = [
	"TV",
	"TV_Short",
	"Movie",
	"Special",
	"OVA",
	"ONA",
	"Music",
];

export const formatItemsManga: string[] = [
	"Manga (Japan)",
	"Manga (South Korean)",
	"Manga (Chinese)",
	"manga",
	"manwha",
	"manhua",
	"One shot",
	"Novel",
];

export const tagCategories: string[] = [
	"Cast",
	"Cast / Main Cast",
	"Cast / Traits",
	"Demographic",
	"Setting",
	"Setting / Scene",
	"Setting / Time",
	"Setting / Universe",
	"Technical",
	"Theme / Action",
	"Theme / Arts",
	"Theme / Arts-Music",
	"Theme / Comedy",
	"Theme / Drama",
	"Theme / Fantasy",
	"Theme / Game",
	"Theme / Game-Card & Board Game",
	"Theme / Game-Sport",
	"Theme / Other",
	"Theme / Other-Organisations",
	"Theme / Other-Vehicle",
	"Theme / Romance",
	"Theme / Sci Fi",
	"Theme / Sci Fi-Mecha",
	"Theme / Slice Of Life",
];

export const tags: string[] = [
	"Polyamorous",
	"Anti-Hero",
	"Ensemble Cast",
	"Estranged Family",
	"Female Protagonist",
	"Male Protagonist",
	"Primarily Adult Cast",
	"Primarily Animal Cast",
	"Primarily Child Cast",
	"Primarily Female Cast",
	"Primarily Male Cast",
	"Primarily Teen Cast",
	"Age Regression",
	"Agender",
	"Aliens",
	"Amnesia",
	"Angels",
	"Anthropomorphism",
	"Arranged Marriage",
	"Artificial Intelligence",
	"Asexual",
	"Butler",
	"Centaur",
	"Chimera",
	"Chuunibyou",
	"Clone",
	"Cosplay",
	"Crossdressing",
	"Cyborg",
	"Delinquents",
	"Demons",
	"Detective",
	"Dinosaurs",
	"Disability",
	"Dissociative Identities",
	"Dragons",
	"Dullahan",
	"Elf",
	"Fairy",
	"Femboy",
	"Ghost",
	"Goblin",
	"Gods",
	"Gyaru",
	"Hikikomori",
	"Homeless",
	"Idol",
	"Kemonomimi",
	"Kuudere",
	"Maids",
	"Mermaid",
	"Monster Boy",
	"Monster Girl",
	"Nekomimi",
	"Ninja",
	"Nudity",
	"Nun",
	"Office Lady",
	"Oiran",
	"Ojou-Sama",
	"Orphan",
	"Pirates",
	"Robots",
	"Samurai",
	"Shrine Maiden",
	"Skeleton",
	"Succubus",
	"Tanned Skin",
	"Teacher",
	"Tomboy",
	"Transgender",
	"Tsundere",
	"Twins",
	"Vampire",
	"Veterinarian",
	"Vikings",
	"Villainess",
	"VTuber",
	"Werewolf",
	"Witch",
	"Yandere",
	"Zombie",
	"Josei",
	"Kids",
	"Seinen",
	"Shoujo",
	"Shounen",
	"Matriarchy",
	"Bar",
	"Boarding School",
	"Circus",
	"Coastal",
	"College",
	"Desert",
	"Dungeon",
	"Foreign",
	"Inn",
	"Konbini",
	"Natural Disaster",
	"Office",
	"Outdoor",
	"Prison",
	"Rural",
	"School",
	"School Club",
	"Snowscape",
	"Urban",
	"Work",
	"Achronological Order",
	"Anachronism",
	"Ancient China",
	"Dystopian",
	"Historical",
	"Time Skip",
	"Afterlife",
	"Alternate Universe",
	"Augmented Reality",
	"Omegaverse",
	"Post-Apocalyptic",
	"Space",
	"Urban Fantasy",
	"Virtual World",
	"4-Koma",
	"Achromatic",
	"Advertisement",
	"Anthology",
	"CGI",
	"Episodic",
	"Flash",
	"Full CGI",
	"Full Color",
	"No Dialogue",
	"Non-Fiction",
	"POV",
	"Puppetry",
	"Rotoscoping",
	"Stop Motion",
	"Archery",
	"Battle Royale",
	"Espionage",
	"Fugitive",
	"Guns",
	"Martial Arts",
	"Spearplay",
	"Swordplay",
	"Acting",
	"Calligraphy",
	"Classic Literature",
	"Drawing",
	"Fashion",
	"Food",
	"Makeup",
	"Photography",
	"Rakugo",
	"Writing",
	"Band",
	"Dancing",
	"Musical",
	"Parody",
	"Satire",
	"Slapstick",
	"Surreal Comedy",
	"Bullying",
	"Class Struggle",
	"Coming Of Age",
	"Conspiracy",
	"Kingdom Management",
	"Rehabilitation",
	"Revenge",
	"Suicide",
	"Tragedy",
	"Alchemy",
	"Body Swapping",
	"Cultivation",
	"Fairy Tale",
	"Henshin",
	"Isekai",
	"Kaiju",
	"Magic",
	"Mythology",
	"Necromancy",
	"Shapeshifting",
	"Steampunk",
	"Super Power",
	"Superhero",
	"Wuxia",
	"Youkai",
	"Board Game",
	"E-Sports",
	"Video Games",
	"Card Battle",
	"Go",
	"Karuta",
	"Mahjong",
	"Poker",
	"Shogi",
	"Acrobatics",
	"Airsoft",
	"American Football",
	"Athletics",
	"Badminton",
	"Baseball",
	"Basketball",
	"Boxing",
	"Cheerleading",
	"Cycling",
	"Fencing",
	"Fishing",
	"Fitness",
	"Football",
	"Golf",
	"Handball",
	"Ice Skating",
	"Judo",
	"Lacrosse",
	"Parkour",
	"Rugby",
	"Scuba Diving",
	"Skateboarding",
	"Sumo",
	"Surfing",
	"Swimming",
	"Table Tennis",
	"Tennis",
	"Volleyball",
	"Wrestling",
	"Adoption",
	"Animals",
	"Astronomy",
	"Autobiographical",
	"Biographical",
	"Body Horror",
	"Cannibalism",
	"Chibi",
	"Cosmic Horror",
	"Crime",
	"Crossover",
	"Death Game",
	"Denpa",
	"Drugs",
	"Economics",
	"Educational",
	"Environmental",
	"Ero Guro",
	"Filmmaking",
	"Found Family",
	"Gambling",
	"Gender Bending",
	"Gore",
	"Language Barrier",
	"LGBTQ+ Themes",
	"Lost Civilization",
	"Marriage",
	"Medicine",
	"Memory Manipulation",
	"Meta",
	"Mountaineering",
	"Noir",
	"Otaku Culture",
	"Pandemic",
	"Philosophy",
	"Politics",
	"Proxy Battle",
	"Reincarnation",
	"Religion",
	"Royal Affairs",
	"Slavery",
	"Software Development",
	"Survival",
	"Terrorism",
	"Torture",
	"Travel",
	"War",
	"Assassins",
	"Criminal Organization",
	"Cult",
	"Firefighters",
	"Gangs",
	"Mafia",
	"Military",
	"Police",
	"Triads",
	"Yakuza",
	"Aviation",
	"Cars",
	"Mopeds",
	"Motorcycles",
	"Ships",
	"Tanks",
	"Trains",
	"Age Gap",
	"Bisexual",
	"Boys' Love",
	"Female Harem",
	"Heterosexual",
	"Love Triangle",
	"Male Harem",
	"Mixed Gender Harem",
	"Teens' Love",
	"+Unrequited Love",
	"Yuri",
	"Cyberpunk",
	"Space Opera",
	"Time Loop",
	"Time Manipulation",
	"Tokusatsu",
	"Real Robot",
	"Super Robot",
	"Agriculture",
	"Cute Boys Doing Cute Things",
	"Cute Girls Doing Cute Things",
	"Family Life",
	"Horticulture",
	"Iyashikei",
];
